### PR TITLE
Windows: update to libgsl 2.7 + ucrt support

### PR DESCRIPTION
**Pull request by jeroen**
See https://github.com/rwinlib/gsl/releases/tag/v2.7

### CODE REVIEW

**Comment by eddelbuettel** [comment]
This looks good and very timely.  Is this how one enables UCRT support?  Are there other docs?  Can one test it?   We have an artifact for TileDB and I was wondering how to hook it up / test it....

**Comment by jeroen** [comment]
The `Makevars.ucrt` file is picked up by the experimental R-devel that Tomas uses for UCRT toolchains. 

Sadly we can only test this manually right now. They have promised a check machine but that doesn't seem to have happend yet. Hopefully soon.

I have already looked into tiledb already, but there seems to be a threading bug in the ucrt toolchain that Tomas uses. I think he plans to update soon, and then we can get it fixed.

**Comment by eddelbuettel** [comment]
Very nice, thank you.  Did you notice our artifact or did you build your own for ucrt?

Shucks about the missing build/test machine.  In which case I move along with a new release -- which will bring us arm64 "M1" support -- and wait for news on the threading issue.

**Review by eddelbuettel — APPROVED** [review]
Looks good. I'll add the missing ChangeLog and NEWS entries (and reformat the R file :grin:)

**Comment by eddelbuettel** [comment]
How come it built at UCRT already?  Does it default to the non-UCRT build and hopes for the best?

image

**Comment by jeroen** [comment]
Currently Tomas [patches](https://www.r-project.org/nosvn/winutf8/ucrt3/patches/CRAN/) the package on his end, to make it build on his local machine. But that doesn't work on other machines or CI services.

**Comment by eddelbuettel** [comment]
Right.  But then UCRT is also labelled "experimental" and called unsupported til at least R 4.2.  Still, if and when it is easy to accomodate may as well.  Will ship RcppGSL now -- related btw is the utter build failure of RcppZiggurat at your end.  It should just use RcppGSL.  Any idea?

**Pull request merged**
